language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2
  - 7.3.24

matrix:
  fast_finish: true

before_install:
  - composer self-update
  - if [ "$GITHUB_COMPOSER_AUTH" ]; then composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH; fi

install:
  - composer install --prefer-dist --no-interaction

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/php-cs-fixer fix --diff --dry-run --ansi
  - vendor/bin/phpstan analyze --memory-limit=-1 --ansi
  - vendor/bin/phpmd src text ruleset.xml --suffixes php
  - vendor/bin/phpunit --stderr --colors=always --coverage-clover=coverage.xml

after_script:
  # Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
